version: "3"
services:
  app:
    image: "full-stack-demo:dev"
    container_name: full-stack-demo-dev
    environment:
      DB_PASSWORD:
      DB_HOST: database
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - "${PWD}/backend:/app"
    depends_on:
      - database
    command: /bin/sh
  database:
    image: "postgres:16.0-alpine"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "app_pg_data:/var/lib/postgresql/data"
volumes:
  app_pg_data:
